import pandas as pd
data=pd.read_csv("Salaries.csv")
df=pd.DataFrame(data)
print(df.info())
print(df.describe().transpose())
print(df.head())
print(df.tail())
print(df['BasePay'].mean())
print(df['BasePay'].min())
print(df['JobTitle'].argmin())
print(df[df['JobTitle']=="CAPTAIN III (POLICE DEPARTMENT)"]['TotalPayBenefits'].max())
print(df[df['TotalPayBenefits']==df['TotalPayBenefits'].max()]['EmployeeName'])
print(df.groupby('Year').max())
print(df['JobTitle'].nunique())
print(df['JobTitle'].value_counts().head(3))
print(df[df['Year']==2013]['JobTitle'].value_counts().count())